# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Nikhil
tagline:          ''
description:      'Full-stack engineer. Machine that converts coffee into insights.'
url:              http://nikhilRP.github.io
baseurl:          '/'
paginate:         5

author:
  name:           'Nikhil'
  url:            

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/nikhilRP/nikhilrp.github.io
